
export const enum ProblemCode {
    All = "*", // Wildcard matching all codes. Not used in diagnostics, but can be used in filters.
    Unknown = "P1000", // Not used. Use the more specific codes below instead.
    UnexpectedToken = "P1001", // Code could not be parsed because an unexpected token was found.
    UndefinedSymbol = "P1002", // Not used. Use the more specific codes below instead.
    UnusedSymbol = "P1003", // Symbol is declared but never used.
    DuplicateSymbol = "P1004", // Symbol is declared more than once with same name.
    TooFewArgumentCount = "P1005", // Not enough arguments provided to a function or method.
    TypeError = "P1006", // Type does not match the expected or permitted type.
    DeprecatedSymbol = "P1007", // Usage of a symbol that has been marked with `@deprecated` or `#[Deprecated]`.
    UndefinedVariable = "P1008", // Variable is used before it is declared.
    UndefinedType = "P1009", // Type cannot be found in project or has not been indexed.
    UndefinedFunction = "P1010", // Function cannot be found in project or has not been indexed.
    UndefinedConstant = "P1011", // Constant cannot be found in project or has not been indexed.
    UndefinedClassConstant = "P1012", // Class constant cannot be found on scope type.
    UndefinedMethod = "P1013", // Method cannot be found on scope type.
    UndefinedProperty = "P1014", // Property cannot be found on scope type.
    MultipleVisibilityModifiers = "P1015", // More than one visibility modifier is used on a class member.
    FinalModifierNotAllowed = "P1016", // Final modifier is not allowed in this context.
    PrivateMethodCannotBeAbstract = "P1017", // Private methods cannot be abstract except in traits.
    AbstractModifierNotAllowed = "P1018", // Abstract modifier is not allowed in this context.
    InterfaceMethodsMustBePublic = "P1019", // Methods in an interface must be public.
    MethodBodyExpected = "P1020", // Method body is expected in non abstract/interface method.
    MethodBodyNotAllowed = "P1021", // Method body is not allowed in abstract/interface methods.
    SyntaxNotAvailableInTargetVersion = "P1022", // `intelephense.environment.phpVersion` is set to a version of PHP that does not support the syntax being used.
    ReservedWord = "P1023", // Reserved word is used in an invalid context.
    ExpressionNotWritable = "P1024", // Expression cannot be assigned a value.
    EmptyArrayDestructure = "P1025", // Array destructuring is empty.
    KeyExpectedInReadContext = "P1026", // Array key is expected in read context.
    UnexpectedIndentationLevel = "P1027", // Heredoc indentation level is not of expected length.
    InvalidIndentation = "P1028", // Heredoc indentation is not valid (e.g. contains mix of space and tabs).
    AbstractMethodInNonAbstractClass = "P1029", // Abstract method is declared in a non-abstract class.
    UsingThisInNonObjectContext = "P1030", // `$this` is used outside object context.
    RealCast = "P1031", // `(real)` cast is deprecated in PHP 7.4+.
    UnsetCast = "P1032", // `(unset)` cast is deprecated in PHP 7.2+.
    NestedTernaryExpression = "P1033", // Unparenthesized nested ternary is deprecated in PHP 7.4+.
    ArrayOrStringOffsetAccessWithCurlyBraces = "P1034", // Curly-brace array or string offset access is deprecated in PHP 7.4+.
    UseOfParentInClassWithNoParent = "P1035", // `parent` is used in a class with no parent.
    NonStaticMethodCalledStatically = "P1036", // Non-static method is called statically.
    NotAllMethodsImplemented = "P1037", // Type does not implement all required inherited abstract or interface methods.
    MethodSignatureNotCompatible = "P1038", // Method signature is incompatible with inherited method signature.
    CannotOverrideFinalMember = "P1039", // Final method, property, or class constant is overridden.
    KeywordInNamespaceName = "P1040", // Namespace name uses a keyword before PHP 8.0.
    CannotDeclarePropertyPromotionOutsideOfConstructor = "P1041", // Constructor property promotion is used outside a constructor in PHP 8.0+.
    CannotUsePositionalArgumentAfterNamedArgument = "P1042", // Positional argument appears after a named argument in PHP 8.0+.
    NamedArgumentOverwritesPreviousArgument = "P1043", // Named argument overwrites an earlier positional or named argument in PHP 8.0+.
    UnknownNamedArgument = "P1044", // Named argument does not match any parameter in PHP 8.0+.
    CannotUseReadonlyAsModifier = "P1045", // `readonly` is not a valid modifier for context in PHP 8.1+.
    ReadonlyPropertyMustHaveType = "P1046", // Readonly property is missing a declared type in PHP 8.1+.
    ReadonlyPropertyCannotHaveDefaultValue = "P1047", // Readonly property declares a default value in PHP 8.1+.
    TypeCannotBeUsedInThisContext = "P1048", // Type is not permitted in this declaration context.
    EnumCaseCanOnlyBeUsedInEnum = "P1049", // `case` is used outside an enum in PHP 8.1+.
    EnumCaseOfBackedEnumMustHaveValue = "P1050", // Backed enum case is missing a value in PHP 8.1+.
    EnumBackingTypeMustBeIntOrString = "P1051", // Enum backing type must be `int` or `string` in PHP 8.1+.
    EnumCaseOfNonBackedEnumMustNotHaveValue = "P1052", // Non-backed enum case declares a value in PHP 8.1+.
    CannotCreateClosureForNewExpression = "P1053", // First-class callable syntax cannot be used in a `new` expression in PHP 8.1+.
    CannotCombineNullsafeOperatorWithClosureCreation = "P1054", // First-class callable syntax cannot be combined with nullsafe access in PHP 8.1+.
    TraitsCannotHaveConstants = "P1055", // Trait constants are not available before PHP 8.2.
    CannotModifyPropertyFromScope = "P1056", // Property cannot be modified from the current scope because of set visibility restrictions.
    StaticPropertyCannotBeReadonly = "P1057", // Static property is declared `readonly` in PHP 8.1+.
    ReadonlyClassCannotDeclareStaticProperties = "P1058", // Readonly class declares a static property in PHP 8.2+.
    NonReadonlyClassCannotExtendReadonlyClass = "P1059", // Non-readonly class extends a readonly class in PHP 8.2+.
    ReadonlyClassCannotExtendNonReadonlyClass = "P1060", // Readonly class extends a non-readonly class in PHP 8.2+.
    CannotRedeclareReadonlyPropertyAsNonReadonly = "P1061", // Readonly property is redeclared as non-readonly in PHP 8.1+.
    CannotRedeclareNonReadonlyPropertyAsReadonly = "P1062", // Non-readonly property is redeclared as readonly in PHP 8.1+.
    DollarCurlyOpenDeprecated = "P1063", // `${}` string interpolation is deprecated in PHP 8.2+.
    CannotBeUsedAsAStandaloneType = "P1064", // Type cannot be used by itself in type declaration for target PHP version.
    RedundantType = "P1065", // Union or intersection type contains a redundant member.
    CannotUseSetVisibilityModifierOnNonProperty = "P1066", // Asymmetric set visibility is used on a non-property in PHP 8.4+.
    AvisPropMustHaveType = "P1067", // Asymmetric visibility property is missing a declared type in PHP 8.4+.
    SetVisibilityMustBeEqualToOrLessThanGetVisibility = "P1068", // Set visibility is broader than get visibility in PHP 8.4+.
    StaticPropertyCannotHaveAvis = "P1069", // Static property uses asymmetric visibility where disallowed in PHP 8.4.
    MemberVisibilityMustBeSameOrLessRestrictiveThanBaseMemberVisibility = "P1070", // Overriding member visibility is more restrictive than the base member.
    CannotSpecifySetVisibilityForVirtualPropertyWithNoSetHook = "P1071", // Get-only virtual property declares set visibility in PHP 8.4+.
    VirtualPropertyCannotHaveDefaultValue = "P1072", // Virtual property declares a default value in PHP 8.4+.
    CannotIndirectlyModifyProperty = "P1073", // Property cannot be modified indirectly. For example, assigning a non-reference get hooked property by reference.
    InvalidPropertyHookSignature = "P1074", // Property hook signature is invalid in PHP 8.4+.
    NotAllPathsReturnValue = "P1075", // Function or method with a return value does not return a value on all paths.
    CannotUnsetHookedProperty = "P1076", // Hooked property cannot be unset in PHP 8.4+.
    PropertyTypeIncompatibleWithBasePropertyType = "P1077", // Property type is incompatible with the inherited property type.
    ImplicitlyNullableParameterDeprecated = "P1078", // Non-nullable parameter with `= null` default argument specifier is deprecated in PHP 8.4+.
    HookedPropertiesCannotBeReadonly = "P1079", // Hooked property cannot also be readonly in PHP 8.4+.
    CannotAccessMemberWithVisibility = "P1080", // Member cannot be accessed because of private or protected get visibility.
    StaticModifierNotAllowed = "P1081", // `static` modifier is used where it is not allowed.
    InterfacesMayOnlyContainHookedProperties = "P1082", // Interface property must be a hooked property in PHP 8.4+.
    CaseStatementsFollowedBySemicolonDeprecated = "P1083", // `case` or `default` in a `switch` statement followed by `;` is deprecated in PHP 8.5+.
    NonCanonicalCastDeprecated = "P1084", // Non-canonical cast spelling is deprecated in PHP 8.5+. For example `(int)` is canonical, but `(integer)` is not.
    BacktickOperatorDeprecated = "P1085", // Backtick shell operator is deprecated in PHP 8.5+.
    AttemptingToUseNonAttributeClassAsAttribute = "P1086", // Non-attribute class is used as an attribute in PHP 8.0+.
    InvalidAttributeTarget = "P1087", // Attribute is applied to an unsupported target in PHP 8.0+.
    AttributeCannotBeRepeated = "P1088", // Non-repeatable attribute is applied more than once in PHP 8.0+.
    ConstantExpressionContainsInvalidOperations = "P1089", // Constant expression uses an operation that is not allowed in that context.
    ClosuresInConstantExpressionsMustBeStatic = "P1090", // Closure in a constant expression must be `static` in PHP 8.5+.
    CannotUseVariablesInConstantExpression = "P1091", // Variables cannot be captured (`use`d) in a constant expression closure in PHP 8.5+.
    ArrowFunctionsOnRhsOfPipeMustBeParenthesised = "P1092", // Arrow function on the right-hand side of `|>` must be parenthesized in PHP 8.5+.
    TraitMethodCollision = "P1093", // Type composition produces colliding trait methods of the same name.
    CannotExtendImplementUseType = "P1094", // Type attempts to extend, implement, or use an invalid kind or final type.
    DuplicateExtendImplementUseType = "P1095", // Duplicate type appears in an extends, implements, or use list.
    EnumCannotImplementMagicMethod = "P1096", // Enum implements a forbidden magic method in PHP 8.1+.
    EnumCannotIncludeProperties = "P1097", // Enum declares properties in PHP 8.1+.
    CannotInstantiateType = "P1098", // Abstract type or non-instantiable kind is instantiated.
    DefiningCustomAssertFunctionDeprecated = "P1099", // Defining a custom `assert()` function is deprecated in PHP 7.3+.
    FunctionNameNotAllowed = "P1100", // Function name is forbidden, such as a reserved built-in or special name.
    OptionalParameterDeclaredBeforeRequiredParameterDeprecated = "P1101", // Optional parameter before a required one is deprecated in PHP 8.0+.
    ClassConstantTypeNotCompatible = "P1102", // Typed class constant is incompatible with an inherited constant in PHP 8.3+.
    DuplicateEnumCaseValue = "P1103", // Backed enum reuses a case value in PHP 8.1+.
    BreakAndContinueCanOnlyBeUsedInLoopOrSwitchContext = "P1104", // `break` or `continue` is used outside a loop or switch context.
    NamespaceDeclarationMustBeFirstStatementOrImmediatelyAfterDeclare = "P1105", // Namespace declaration is not first or immediately after `declare`.
    CannotMixBracketedAndUnbracketedNamespaceDeclarations = "P1106", // Bracketed and unbracketed namespace declarations are mixed.
    NoCodeMayExistsOutsideOfBracketedNamespace = "P1107", // Code exists outside a bracketed namespace block.
    UnreachableCode = "P1108", // Control flow makes the code unreachable.
    CannotDeclareReturnType = "P1109", // Method declares a return type where PHP forbids one, such as `__construct`.
    CompositionIncompatibleProperty = "P1110", // Types used in composition contribute incompatible properties of same name.
    CompositionIncompatibleClassConstant = "P1111", // Types used in composition contribute incompatible class constants of same name.
    CompositionIncompatibleMethod = "P1112", // Types used in composition contribute incompatible methods of same name.
    VariadicParamCannotHaveDefaultArg = "P1113", // Variadic parameter declares a default argument.
    OnlyVariablesShouldBePassedByReference = "P1114", // Non-variable expression is passed to a by-reference parameter.
    CannotUseKeylessArrayOperatorOnString = "P1115", // `[]` array append operator is used on a string.
    PossibleUndefinedVariable = "P1116", // Variable may be undefined on some control-flow paths.
    VoidCastCannotBeUsedInContext = "P1117", // `(void)` cast is used where a value is required in PHP 8.5+.
    DuplicateArrayKey = "P1118", // Array literal contains the same key more than once.
    TooManyArgumentCount = "P1119", // Too many arguments are passed to a function or method.
    OnlyTheLastParameterCanBeVariadic = "P1120", // Variadic parameter is not the last parameter.
    IncorrectStringConcatenationOperator = "P1121", // Using `+` for string literal concatenation.
    AssignmentInConditionalContext = "P1122", // Assignment appears in a conditional expression and may be unintended.
    DuplicateBranchExpression = "P1123", // Match arm or conditional branch expression is duplicated.
    LoopVariableOverwritesPreviousDeclaration = "P1124", // Loop variable shadows a parameter or outer loop variable.
    VoidAssignment = "P1125", // Result of a `void` expression or call is assigned.
    ReturnValueNotConsumed = "P1126", // Result of a `#[NoDiscard]` call is ignored in PHP 8.5+.
    NoDiscardCannotBeUsedInContext = "P1127", // `#[NoDiscard]` is applied where PHP forbids it in PHP 8.5+.
    OverrideHasNoMatchingParentMethod = "P1128", // `#[Override]` has no matching parent method in PHP 8.3+.
    PhpDocParseError = "P1129", // PHPDoc contains a parse error.
    PhpDocUnknownParamTagParamName = "P1130", // PHPDoc `@param` tag names a parameter that does not exist.
    PhpDocIncompatibleDocumentedType = "P1131", // PHPDoc type is incompatible with the declared or inferred type and may be incorrectly suppressing type errors.
    NoTypeInformation = "P1132", // Symbol has no type information available and will default to `mixed`.
    PhpDocUndefinedType = "P1133", // PHPDoc references a type that cannot be found in the project or has not been indexed.
    CircularReference = "P1134", // Symbol participates in a circular reference.
}
